#!/bin/sh

set -e
if [ -f /usr/bin/QtAutomotiveClusterDemo ]; then
        QTDEMO="QtAutomotiveClusterDemo -qws"
        QTDEMO_KILL="QtAutomotiveClusterDemo"
	export QWS_DISPLAY="LinuxFb:/dev/fb:genericcolors"
        export QWS_KEYBOARD="USB:/dev/input/event-keyboard"
        export QWS_MOUSE_PROTO="LinuxInput:/dev/input/event-mouse"
else
	if [ -f /usr/bin/qtdeqtdemoEmo ]; then
		QTDEMO="qtdemo > /var/log/Xsession.log 2> &1"
        	QTDEMO_KILL="qtdemo"

	else
		QTDEMO="qtdemoE -qws"
	        QTDEMO_KILL="qtdemoE"
		export QWS_DISPLAY="LinuxFb:/dev/fb:genericcolors"
		export QWS_KEYBOARD="USB:/dev/input/event-keyboard"
		export QWS_MOUSE_PROTO="LinuxInput:/dev/input/event-mouse"
	fi
fi
case "$1" in
  start)
	echo "Starting qtdemo"
#	if [ -f /etc/profile.d/tslib.sh ]; then
#		source /etc/profile.d/tslib.sh
#		:
#	fi
#	if [ -e "$TSLIB_TSDEVICE" ]; then
#		if [ ! -f /etc/pointercal ]; then
#			/usr/bin/ts_calibrate
#		fi
#		if [ "$QTDEMO" == qtdemo ]; then
#			Xorg &
#			export DISPLAY=:0
#			$QTDEMO &
#		else
#			QWS_MOUSE_PROTO=tslib:$TSLIB_TSDEVICE $QTDEMO &
#		fi
#	else
		if [ "$QTDEMO" == qtdemo ]; then
			Xorg &
			export DISPLAY=:0
		fi
		$QTDEMO &
#	fi
	;;
  stop)
	echo "Stopping qtdemo"
	if [ "$QTDEMO" == qtdemo ]; then
		killall Xorg
		killall qtdemo
	else
		killall $QTDEMO_KILL
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "usage: $0 { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
